In [94]:
import pandas as pd

### LOADING DATA

In [95]:
data = pd.read_excel('seekingalpha_attachment.xlsx',sheet_name=2,header=5,skipfooter=15)
data.head()

,Name,Symbol,Sector,Industry,Yrs,Seq,DR,SP,Price,Yield,...,%,Beta,Low,High,MMA,MMA.1,OTC,Began,Survived,ROA
0,Aaron's Inc.,AAN,Consumer Discretionary,Specialty Retail,17,219,-,-,39.33,0.406814,...,2.194918,0.31,-0.33,-49.99,-30.83,-35.34,NaN,2004,1,1.0
1,AmerisourceBergen Corp.,ABC,Health Care,Health Care Providers & Services,16,248,-,-,84.32,1.992410,...,11.204512,1.03,19.52,-13.52,-5.40,-2.09,NaN,2006,1,1.7
2,Accenture plc,ACN,Information Technology,IT Services,15,266,-,-,180.59,1.771970,...,10.931130,1.01,12.59,-16.54,-13.42,-7.31,NaN,2006,1,16.4
3,Acme United Corp.,ACU,Industrials,Commercial Services & Supplies,16,230,-,-,23.22,2.067183,...,12.746565,1.36,45.12,-6.80,-2.04,7.92,NaN,2005,1,4.5
4,Analog Devices Inc.,ADI,Information Technology,Semiconductors & Semiconductor Equipment,18,195,-,-,109.05,2.274186,...,12.835791,1.42,14.18,-14.34,-7.20,-2.93,NaN,2003,1,NaN

### DATA PREPARATION

In [96]:
str_to_float_columns = ['Yrs','Price','Yield','Year','1-yr','3-yr','5-yr','10-yr','P/E','ROE','($Mil)','Equity','Survived','ROA']
for column in str_to_float_columns:
    data[column] = pd.to_numeric(data[column])
    
data = data[['Name','Symbol','Sector','Industry','Yrs','Price','Yield','Year','1-yr','3-yr','5-yr','10-yr','P/E','ROE','($Mil)','Equity','Survived','ROA']]
data = data.rename(columns={'Yrs':'Years','Year':'Payouts Per Year','Yield':'Dividend Yield','1-yr':'Dividend Growth Rate in 1-yr',
                   '3-yr':'Dividend Growth Rate in 3-yr','5-yr':'Dividend Growth Rate in 5-yr','10-yr':'Dividend Growth Rate in 10-yr',
                   '($Mil)':'Market Capitalization($Mil)','P/E':'Price/Earnings','ROE':'Return on Equity','Equity':'Dept/Equity',
                   'Survived':'Number of Survived Recessions','ROA':'Return on Assets'})
data

,Name,Symbol,Sector,Industry,Years,Price,Dividend Yield,Payouts Per Year,Dividend Growth Rate in 1-yr,Dividend Growth Rate in 3-yr,Dividend Growth Rate in 5-yr,Dividend Growth Rate in 10-yr,Price/Earnings,Return on Equity,Market Capitalization($Mil),Dept/Equity,Number of Survived Recessions,Return on Assets
0,Aaron's Inc.,AAN,Consumer Discretionary,Specialty Retail,17,39.33,0.406814,4,16.666667,11.868894,10.236627,11.936406,13.423208,1.7,2770.00,0.20,1,1.0
1,AmerisourceBergen Corp.,ABC,Health Care,Health Care Providers & Services,16,84.32,1.992410,4,3.896104,4.927680,9.966241,20.890138,27.376623,22.1,17280.00,1.41,1,1.7
2,Accenture plc,ACN,Information Technology,IT Services,15,180.59,1.771970,4,7.168459,8.981572,8.924936,14.831488,24.110814,34.3,119760.00,0.00,1,16.4
3,Acme United Corp.,ACU,Industrials,Commercial Services & Supplies,16,23.22,2.067183,4,9.090909,6.265857,7.781807,9.149343,15.689189,9.5,78.48,0.76,1,4.5
4,Analog Devices Inc.,ADI,Information Technology,Semiconductors & Semiconductor Equipment,18,109.05,2.274186,4,12.500000,8.738037,7.854534,10.442538,33.761610,NaN,40740.00,0.47,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,Wyndham Destinations Inc.,WYND,Consumer Discretionary,"Hotels, Restaurants & Leisure",10,39.90,4.511278,4,-4.761905,-3.451062,5.154750,27.384109,8.507463,-78.3,3660.00,NaN,0,6.1
290,Xcel Energy,XEL,Utilities,Electric Utilities,17,62.32,2.759949,4,6.333333,5.978710,6.212526,5.153404,23.606061,10.1,33350.00,1.42,1,2.6
291,Xilinx Inc.,XLNX,Information Technology,Semiconductors & Semiconductor Equipment,17,83.49,1.772667,4,2.797203,4.181673,6.360095,9.746059,24.922388,32.4,21270.00,0.00,1,17.4
292,Xylem Inc.,XYL,Industrials,Machinery,10,77.34,1.344712,4,14.285714,15.714187,13.396658,NaN,34.995475,20.2,13950.00,0.81,0,7.7
293,York Water Company,YORW,Utilities,Water Utilities,22,42.29,1.704422,4,4.021609,3.678663,3.903885,3.238765,37.424779,11.4,548.92,0.76,2,4.2

### IMPOSING RESTRICTIONS IN ORDER TO SELECT LISTED COMPANIES THAT I AM INTERESTED IN

In [100]:
data = data.loc[(data['Dividend Yield'] > 1.5) & 
                (data['Dividend Yield'] < 7) & 
                (data['Price/Earnings'] < 20) & 
                (data['Return on Equity'] > 10) & 
                (data['Market Capitalization($Mil)'] > 10000) & 
                (data['Dept/Equity'] < 1)]
data

,Name,Symbol,Sector,Industry,Years,Price,Dividend Yield,Payouts Per Year,Dividend Growth Rate in 1-yr,Dividend Growth Rate in 3-yr,Dividend Growth Rate in 5-yr,Dividend Growth Rate in 10-yr,Price/Earnings,Return on Equity,Market Capitalization($Mil),Dept/Equity,Number of Survived Recessions,Return on Assets
13,Allstate Corp.,ALL,Financials,Insurance,10,105.25,2.052257,4,12.000000,14.962303,11.842691,9.374633,7.480455,12.7,34050.0,0.29,0,2.3
19,TD Ameritrade Holding Corp.,AMTD,Financials,Capital Markets,10,42.23,2.936301,4,30.107527,20.590222,18.862001,NaN,11.763231,23.2,23980.0,0.00,0,4.7
32,Best Buy Corp.,BBY,Consumer Discretionary,Specialty Retail,17,75.65,2.908130,4,8.333333,20.301820,22.050742,13.288195,13.389381,46.9,19940.0,0.40,1,10.3
39,BlackRock Inc.,BLK,Financials,Capital Markets,11,463.01,3.136001,4,9.816972,12.951712,11.324647,15.515945,16.263084,13.1,73140.0,0.18,0,2.6
60,Cummins Inc.,CMI,Industrials,Machinery,14,151.29,3.466191,4,10.405405,7.013304,11.772097,21.486362,10.491678,28.8,22690.0,0.32,1,11.3
69,Cisco Systems Inc.,CSCO,Information Technology,Communications Equipment,10,39.93,3.606311,4,7.812500,11.707234,13.273801,NaN,14.467391,31.5,171370.0,0.45,0,11.7
91,Eaton Corp. plc,ETN,Industrials,Electrical Equipment,11,90.72,3.218695,4,7.575758,7.595597,7.699194,11.002263,17.280000,13.7,37560.0,0.51,0,7.0
101,Fifth Third Bancorp,FITB,Financials,Banks,10,24.40,4.426230,4,35.294118,20.181417,12.523577,36.827308,7.261905,11.3,17570.0,0.74,0,1.2
113,Hasbro Inc.,HAS,Consumer Discretionary,Leisure Products,16,77.25,3.521036,4,8.536585,10.294214,9.578389,12.808579,19.312500,18.0,11620.0,0.93,1,6.0
122,Hartford Financial Services Group Inc.,HIG,Financials,Insurance,10,49.95,2.602603,4,14.285714,12.624788,13.754383,9.826802,8.825088,11.3,18010.0,0.31,0,2.4
171,Magna International Inc.,MGA,Consumer Discretionary,Auto Components,11,45.82,3.491925,4,10.606061,13.444719,13.948301,41.616558,8.438306,23.2,14450.0,0.34,0,9.5
182,Maxim Integrated Products,MXIM,Information Technology,Semiconductors & Semiconductor Equipment,18,55.62,3.451996,4,6.818182,14.269178,11.724088,8.919788,19.515789,44.7,15290.0,0.00,1,21.1
209,Pfizer Inc.,PFE,Health Care,Pharmaceuticals,10,33.42,4.548175,4,5.882353,6.265857,6.724918,6.054048,11.685315,20.5,185620.0,0.81,0,7.9
236,Raytheon Company,RTN,Industrials,Aerospace & Defense,15,188.56,1.999364,4,8.676471,8.818735,9.334358,11.810582,15.805532,27.2,52680.0,0.39,1,10.2
262,Travelers Companies,TRV,Financials,Insurance,15,119.81,2.737668,4,6.600660,7.226075,8.480783,10.136112,12.065458,10.3,30760.0,0.25,1,2.4
263,Tractor Supply Company,TSCO,Consumer Discretionary,Specialty Retail,10,88.51,1.581742,4,13.333333,13.915729,17.392896,NaN,18.993562,36.9,10480.0,0.27,0,10.5
267,UnitedHealth Group Inc.,UNH,Health Care,Health Care Providers & Services,10,254.96,1.694383,4,44.347826,27.993695,28.798440,66.728871,17.804469,25.5,242410.0,0.71,0,8.2
274,Valero Energy Corp.,VLO,Energy,"Oil, Gas & Consumable Fuels",10,66.25,5.916981,4,12.500000,14.471424,27.944800,20.702798,12.111517,11.9,27620.0,0.45,0,5.0